POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzYxMGM1YzYzMzgzZDY3NmU2OWFjMGYiLCJpYXQiOjE2NjczODA5MTB9.sOhv-A_w-ZhrIUIjuq8XMQNsP5mqLewsLyPP0WLW1aE

{
    "title": "prueba back",
    "author": "David",
    "url": "www.facebook.com"
   
    
}